import 'package:flutter/material.dart';

import '../i18n/app_localizations.dart';

enum BoardThemeId {
  classicWood,
  tournamentGreen,
  oceanSlate,
  walnut,
  midnight,
  jungleCanopy,
  coralReef,
  desertSun,
  frostTemple,
  lavaForge,
  sakuraGarden,
  neonCity,
  royalMarble,
  autumnAcademy,
  crystalCavern,
  skyCitadel;

  String get label => switch (this) {
    BoardThemeId.classicWood => 'Classic Wood',
    BoardThemeId.tournamentGreen => 'Tournament Green',
    BoardThemeId.oceanSlate => 'Ocean Slate',
    BoardThemeId.walnut => 'Walnut',
    BoardThemeId.midnight => 'Midnight',
    BoardThemeId.jungleCanopy => 'Jungle Canopy',
    BoardThemeId.coralReef => 'Coral Reef',
    BoardThemeId.desertSun => 'Desert Sun',
    BoardThemeId.frostTemple => 'Frost Temple',
    BoardThemeId.lavaForge => 'Lava Forge',
    BoardThemeId.sakuraGarden => 'Sakura Garden',
    BoardThemeId.neonCity => 'Neon City',
    BoardThemeId.royalMarble => 'Royal Marble',
    BoardThemeId.autumnAcademy => 'Autumn Academy',
    BoardThemeId.crystalCavern => 'Crystal Cavern',
    BoardThemeId.skyCitadel => 'Sky Citadel',
  };

  String localizedLabel(AppStrings strings) => switch (strings.locale) {
    AppLocale.en => label,
    AppLocale.zhHant => switch (this) {
      BoardThemeId.classicWood => '經典木紋',
      BoardThemeId.tournamentGreen => '錦標賽綠',
      BoardThemeId.oceanSlate => '海洋岩板',
      BoardThemeId.walnut => '胡桃木',
      BoardThemeId.midnight => '午夜',
      BoardThemeId.jungleCanopy => '叢林樹冠',
      BoardThemeId.coralReef => '珊瑚海域',
      BoardThemeId.desertSun => '沙漠日輪',
      BoardThemeId.frostTemple => '冰霜神殿',
      BoardThemeId.lavaForge => '熔岩鍛爐',
      BoardThemeId.sakuraGarden => '櫻花庭園',
      BoardThemeId.neonCity => '霓虹都市',
      BoardThemeId.royalMarble => '皇家大理石',
      BoardThemeId.autumnAcademy => '秋日書院',
      BoardThemeId.crystalCavern => '水晶洞窟',
      BoardThemeId.skyCitadel => '天空城塞',
    },
  };
}

class BoardThemeStyle {
  const BoardThemeStyle({
    required this.id,
    required this.pieceSet,
    required this.lightSquare,
    required this.darkSquare,
    required this.frameStart,
    required this.frameEnd,
    required this.labelOnLight,
    required this.labelOnDark,
    required this.whitePiece,
    required this.blackPiece,
    required this.selected,
    required this.selectedBorder,
    required this.lastMove,
    required this.target,
    required this.captureRing,
    required this.textureAlpha,
    required this.backdropTop,
    required this.backdropBottom,
    required this.backdropAccent,
    required this.backdropShadow,
    required this.panelTint,
    this.backdropAsset,
  });

  final BoardThemeId id;
  final ChessPieceSet pieceSet;
  final Color lightSquare;
  final Color darkSquare;
  final Color frameStart;
  final Color frameEnd;
  final Color labelOnLight;
  final Color labelOnDark;
  final Color whitePiece;
  final Color blackPiece;
  final Color selected;
  final Color selectedBorder;
  final Color lastMove;
  final Color target;
  final Color captureRing;
  final double textureAlpha;
  final Color backdropTop;
  final Color backdropBottom;
  final Color backdropAccent;
  final Color backdropShadow;
  final Color panelTint;
  final String? backdropAsset;
}

class ChessPieceSet {
  const ChessPieceSet({
    required this.id,
    required this.label,
    required this.basePath,
    required this.extension,
  });

  final String id;
  final String label;
  final String basePath;
  final String extension;

  String assetFor(String code) => '$basePath/$code.$extension';
}

const cburnettPieceSet = ChessPieceSet(
  id: 'cburnett',
  label: 'Cburnett',
  basePath: 'assets/chess/pieces/cburnett_png',
  extension: 'png',
);

const boardThemeStyles = <BoardThemeId, BoardThemeStyle>{
  BoardThemeId.classicWood: BoardThemeStyle(
    id: BoardThemeId.classicWood,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFF3C885),
    darkSquare: Color(0xFFB36E3E),
    frameStart: Color(0xFF6D4424),
    frameEnd: Color(0xFF52331A),
    labelOnLight: Color(0xFF925B30),
    labelOnDark: Color(0xFFFBE8C2),
    whitePiece: Color(0xFFFFF6EE),
    blackPiece: Color(0xFF505480),
    selected: Color(0x662F80ED),
    selectedBorder: Color(0xAA9AC7FF),
    lastMove: Color(0xD0F6C33C),
    target: Color(0x6A302015),
    captureRing: Color(0x8A2F1A10),
    textureAlpha: 0.11,
    backdropTop: Color(0xFF2C241B),
    backdropBottom: Color(0xFF16120E),
    backdropAccent: Color(0xFFC88943),
    backdropShadow: Color(0xFF2D1710),
    panelTint: Color(0xFF382719),
    backdropAsset: 'assets/chess/themes/classic-wood-club.png',
  ),
  BoardThemeId.tournamentGreen: BoardThemeStyle(
    id: BoardThemeId.tournamentGreen,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFEEEED2),
    darkSquare: Color(0xFF769656),
    frameStart: Color(0xFF38422F),
    frameEnd: Color(0xFF20271C),
    labelOnLight: Color(0xFF6B7F46),
    labelOnDark: Color(0xFFEAF1CF),
    whitePiece: Color(0xFFFFFAEF),
    blackPiece: Color(0xFF303735),
    selected: Color(0x5EF7D04A),
    selectedBorder: Color(0xFFE4C53B),
    lastMove: Color(0xCCF6D962),
    target: Color(0x66404C32),
    captureRing: Color(0x98404C32),
    textureAlpha: 0.04,
    backdropTop: Color(0xFF20291F),
    backdropBottom: Color(0xFF111611),
    backdropAccent: Color(0xFF8DB05F),
    backdropShadow: Color(0xFF172214),
    panelTint: Color(0xFF263120),
    backdropAsset: 'assets/chess/themes/tournament-green-hall.png',
  ),
  BoardThemeId.oceanSlate: BoardThemeStyle(
    id: BoardThemeId.oceanSlate,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFD8E3E8),
    darkSquare: Color(0xFF5E8391),
    frameStart: Color(0xFF2D4953),
    frameEnd: Color(0xFF16282F),
    labelOnLight: Color(0xFF4B7584),
    labelOnDark: Color(0xFFE4F2F6),
    whitePiece: Color(0xFFFFFBF3),
    blackPiece: Color(0xFF223044),
    selected: Color(0x663AA5FF),
    selectedBorder: Color(0xCC9BD7FF),
    lastMove: Color(0xCCF4D35E),
    target: Color(0x66233946),
    captureRing: Color(0x99233946),
    textureAlpha: 0.05,
    backdropTop: Color(0xFF18323D),
    backdropBottom: Color(0xFF0B171C),
    backdropAccent: Color(0xFF6CC7D8),
    backdropShadow: Color(0xFF10212A),
    panelTint: Color(0xFF1D313A),
    backdropAsset: 'assets/chess/themes/ocean-slate-terrace.png',
  ),
  BoardThemeId.walnut: BoardThemeStyle(
    id: BoardThemeId.walnut,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFE7B77A),
    darkSquare: Color(0xFF7B4B2F),
    frameStart: Color(0xFF4C2E1F),
    frameEnd: Color(0xFF2B1A13),
    labelOnLight: Color(0xFF724326),
    labelOnDark: Color(0xFFF0D1A9),
    whitePiece: Color(0xFFFFF0DD),
    blackPiece: Color(0xFF423243),
    selected: Color(0x665EA7FF),
    selectedBorder: Color(0xCCB8D8FF),
    lastMove: Color(0xD0F8D05B),
    target: Color(0x66331E14),
    captureRing: Color(0x98331E14),
    textureAlpha: 0.15,
    backdropTop: Color(0xFF2A1B14),
    backdropBottom: Color(0xFF120C09),
    backdropAccent: Color(0xFFA96938),
    backdropShadow: Color(0xFF22110B),
    panelTint: Color(0xFF2C1F18),
    backdropAsset: 'assets/chess/themes/walnut-study.png',
  ),
  BoardThemeId.midnight: BoardThemeStyle(
    id: BoardThemeId.midnight,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFB7BBC8),
    darkSquare: Color(0xFF3E465B),
    frameStart: Color(0xFF242B3A),
    frameEnd: Color(0xFF121722),
    labelOnLight: Color(0xFF4B5268),
    labelOnDark: Color(0xFFE1E5F1),
    whitePiece: Color(0xFFFFFAF1),
    blackPiece: Color(0xFF151A28),
    selected: Color(0x6656A8FF),
    selectedBorder: Color(0xCC9FD0FF),
    lastMove: Color(0xD0F7C948),
    target: Color(0x66151A28),
    captureRing: Color(0x99151A28),
    textureAlpha: 0.03,
    backdropTop: Color(0xFF171D2B),
    backdropBottom: Color(0xFF090D15),
    backdropAccent: Color(0xFF769BFF),
    backdropShadow: Color(0xFF070912),
    panelTint: Color(0xFF1B2030),
    backdropAsset: 'assets/chess/themes/midnight-observatory.png',
  ),
  BoardThemeId.jungleCanopy: BoardThemeStyle(
    id: BoardThemeId.jungleCanopy,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFE4D7A6),
    darkSquare: Color(0xFF3F7A45),
    frameStart: Color(0xFF314F28),
    frameEnd: Color(0xFF172715),
    labelOnLight: Color(0xFF496633),
    labelOnDark: Color(0xFFEAF4C9),
    whitePiece: Color(0xFFFFF7DD),
    blackPiece: Color(0xFF1E3025),
    selected: Color(0x6657B86F),
    selectedBorder: Color(0xCCBCEB77),
    lastMove: Color(0xD0F0C95B),
    target: Color(0x66305225),
    captureRing: Color(0x99305225),
    textureAlpha: 0.09,
    backdropTop: Color(0xFF173B25),
    backdropBottom: Color(0xFF07150C),
    backdropAccent: Color(0xFF7BC56A),
    backdropShadow: Color(0xFF0B2413),
    panelTint: Color(0xFF172A1E),
    backdropAsset: 'assets/chess/themes/jungle-arena.png',
  ),
  BoardThemeId.coralReef: BoardThemeStyle(
    id: BoardThemeId.coralReef,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFD9F0F0),
    darkSquare: Color(0xFF317F9C),
    frameStart: Color(0xFF285B6C),
    frameEnd: Color(0xFF0D2732),
    labelOnLight: Color(0xFF317485),
    labelOnDark: Color(0xFFE7FAF8),
    whitePiece: Color(0xFFFFF7E8),
    blackPiece: Color(0xFF17283E),
    selected: Color(0x665DD7E8),
    selectedBorder: Color(0xCCB9F4FF),
    lastMove: Color(0xD0F7B678),
    target: Color(0x66274452),
    captureRing: Color(0x99274452),
    textureAlpha: 0.07,
    backdropTop: Color(0xFF08324B),
    backdropBottom: Color(0xFF06131F),
    backdropAccent: Color(0xFF4FD7D8),
    backdropShadow: Color(0xFF061D2B),
    panelTint: Color(0xFF142F3C),
    backdropAsset: 'assets/chess/themes/ocean-arena.png',
  ),
  BoardThemeId.desertSun: BoardThemeStyle(
    id: BoardThemeId.desertSun,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFF4D49C),
    darkSquare: Color(0xFFC07A3D),
    frameStart: Color(0xFF8A4E27),
    frameEnd: Color(0xFF3F2416),
    labelOnLight: Color(0xFF986236),
    labelOnDark: Color(0xFFFFE7B7),
    whitePiece: Color(0xFFFFF3D8),
    blackPiece: Color(0xFF46332E),
    selected: Color(0x66FFB454),
    selectedBorder: Color(0xFFFFD27C),
    lastMove: Color(0xD0FFD15E),
    target: Color(0x664B2D19),
    captureRing: Color(0x994B2D19),
    textureAlpha: 0.10,
    backdropTop: Color(0xFF5A341F),
    backdropBottom: Color(0xFF21120B),
    backdropAccent: Color(0xFFE29A48),
    backdropShadow: Color(0xFF32190D),
    panelTint: Color(0xFF342217),
    backdropAsset: 'assets/chess/themes/desert-arena.png',
  ),
  BoardThemeId.frostTemple: BoardThemeStyle(
    id: BoardThemeId.frostTemple,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFE3EDF4),
    darkSquare: Color(0xFF7EA4BD),
    frameStart: Color(0xFF4B6574),
    frameEnd: Color(0xFF1E303A),
    labelOnLight: Color(0xFF5C7A8C),
    labelOnDark: Color(0xFFF1F9FF),
    whitePiece: Color(0xFFFFFFFF),
    blackPiece: Color(0xFF263241),
    selected: Color(0x667FCBFF),
    selectedBorder: Color(0xFFD0F0FF),
    lastMove: Color(0xD0E7F27A),
    target: Color(0x66304452),
    captureRing: Color(0x99304452),
    textureAlpha: 0.06,
    backdropTop: Color(0xFF203849),
    backdropBottom: Color(0xFF0C141C),
    backdropAccent: Color(0xFF9EDCF2),
    backdropShadow: Color(0xFF142433),
    panelTint: Color(0xFF1B2A34),
    backdropAsset: 'assets/chess/themes/frost-temple.png',
  ),
  BoardThemeId.lavaForge: BoardThemeStyle(
    id: BoardThemeId.lavaForge,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFD8A06A),
    darkSquare: Color(0xFF653735),
    frameStart: Color(0xFF5E2721),
    frameEnd: Color(0xFF1B0E0D),
    labelOnLight: Color(0xFF6F3427),
    labelOnDark: Color(0xFFFFD8A8),
    whitePiece: Color(0xFFFFEAD0),
    blackPiece: Color(0xFF251B1F),
    selected: Color(0x66FF6E40),
    selectedBorder: Color(0xFFFFB25B),
    lastMove: Color(0xD0FFBC4A),
    target: Color(0x66351B18),
    captureRing: Color(0x99351B18),
    textureAlpha: 0.13,
    backdropTop: Color(0xFF341512),
    backdropBottom: Color(0xFF0D0808),
    backdropAccent: Color(0xFFFF7043),
    backdropShadow: Color(0xFF220B09),
    panelTint: Color(0xFF2B1715),
    backdropAsset: 'assets/chess/themes/lava-forge.png',
  ),
  BoardThemeId.sakuraGarden: BoardThemeStyle(
    id: BoardThemeId.sakuraGarden,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFF5DAD8),
    darkSquare: Color(0xFFB86E8B),
    frameStart: Color(0xFF744A5C),
    frameEnd: Color(0xFF30212B),
    labelOnLight: Color(0xFF9B6079),
    labelOnDark: Color(0xFFFFEBEF),
    whitePiece: Color(0xFFFFF5EE),
    blackPiece: Color(0xFF37283B),
    selected: Color(0x66F08DB4),
    selectedBorder: Color(0xFFFFC1D6),
    lastMove: Color(0xD0F5D56A),
    target: Color(0x66432B37),
    captureRing: Color(0x99432B37),
    textureAlpha: 0.08,
    backdropTop: Color(0xFF3B2634),
    backdropBottom: Color(0xFF171018),
    backdropAccent: Color(0xFFF09DBC),
    backdropShadow: Color(0xFF241420),
    panelTint: Color(0xFF2F202B),
    backdropAsset: 'assets/chess/themes/sakura-garden.png',
  ),
  BoardThemeId.neonCity: BoardThemeStyle(
    id: BoardThemeId.neonCity,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFB8E5E8),
    darkSquare: Color(0xFF54336F),
    frameStart: Color(0xFF153C4B),
    frameEnd: Color(0xFF160D22),
    labelOnLight: Color(0xFF39707B),
    labelOnDark: Color(0xFFF3D9FF),
    whitePiece: Color(0xFFFFF5EC),
    blackPiece: Color(0xFF161225),
    selected: Color(0x6659E8FF),
    selectedBorder: Color(0xFFFF62D4),
    lastMove: Color(0xD0FFE95C),
    target: Color(0x66221A36),
    captureRing: Color(0x99221A36),
    textureAlpha: 0.06,
    backdropTop: Color(0xFF102334),
    backdropBottom: Color(0xFF080913),
    backdropAccent: Color(0xFF47DFF0),
    backdropShadow: Color(0xFF090718),
    panelTint: Color(0xFF171A2B),
    backdropAsset: 'assets/chess/themes/neon-city.png',
  ),
  BoardThemeId.royalMarble: BoardThemeStyle(
    id: BoardThemeId.royalMarble,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFF1E6D1),
    darkSquare: Color(0xFF8B6A4A),
    frameStart: Color(0xFF6D563E),
    frameEnd: Color(0xFF221B18),
    labelOnLight: Color(0xFF756046),
    labelOnDark: Color(0xFFFFF0D4),
    whitePiece: Color(0xFFFFF9EA),
    blackPiece: Color(0xFF292332),
    selected: Color(0x66D6B35E),
    selectedBorder: Color(0xFFFFD678),
    lastMove: Color(0xD0FFE182),
    target: Color(0x663B3025),
    captureRing: Color(0x993B3025),
    textureAlpha: 0.07,
    backdropTop: Color(0xFF3A332E),
    backdropBottom: Color(0xFF111014),
    backdropAccent: Color(0xFFD6B35E),
    backdropShadow: Color(0xFF20171A),
    panelTint: Color(0xFF2B2424),
    backdropAsset: 'assets/chess/themes/royal-marble.png',
  ),
  BoardThemeId.autumnAcademy: BoardThemeStyle(
    id: BoardThemeId.autumnAcademy,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFE8C98C),
    darkSquare: Color(0xFF9B5035),
    frameStart: Color(0xFF633827),
    frameEnd: Color(0xFF24140F),
    labelOnLight: Color(0xFF825131),
    labelOnDark: Color(0xFFFFE6AD),
    whitePiece: Color(0xFFFFF1DA),
    blackPiece: Color(0xFF342D24),
    selected: Color(0x66D89942),
    selectedBorder: Color(0xFFFFC961),
    lastMove: Color(0xD0F4D05A),
    target: Color(0x66371F16),
    captureRing: Color(0x99371F16),
    textureAlpha: 0.10,
    backdropTop: Color(0xFF412719),
    backdropBottom: Color(0xFF150D09),
    backdropAccent: Color(0xFFD9863A),
    backdropShadow: Color(0xFF211008),
    panelTint: Color(0xFF302018),
    backdropAsset: 'assets/chess/themes/autumn-academy.png',
  ),
  BoardThemeId.crystalCavern: BoardThemeStyle(
    id: BoardThemeId.crystalCavern,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFD8F0F2),
    darkSquare: Color(0xFF61539A),
    frameStart: Color(0xFF304D64),
    frameEnd: Color(0xFF17132B),
    labelOnLight: Color(0xFF4D6F83),
    labelOnDark: Color(0xFFE7E0FF),
    whitePiece: Color(0xFFFFFFFF),
    blackPiece: Color(0xFF202139),
    selected: Color(0x6677E0D8),
    selectedBorder: Color(0xFFCBB7FF),
    lastMove: Color(0xD0E5F26B),
    target: Color(0x662B254A),
    captureRing: Color(0x992B254A),
    textureAlpha: 0.06,
    backdropTop: Color(0xFF172D3E),
    backdropBottom: Color(0xFF0A0817),
    backdropAccent: Color(0xFF7FE5DA),
    backdropShadow: Color(0xFF100B24),
    panelTint: Color(0xFF1B2134),
    backdropAsset: 'assets/chess/themes/crystal-cavern.png',
  ),
  BoardThemeId.skyCitadel: BoardThemeStyle(
    id: BoardThemeId.skyCitadel,
    pieceSet: cburnettPieceSet,
    lightSquare: Color(0xFFE8ECF2),
    darkSquare: Color(0xFF6F92C0),
    frameStart: Color(0xFF526E8E),
    frameEnd: Color(0xFF1D2D42),
    labelOnLight: Color(0xFF657895),
    labelOnDark: Color(0xFFF7F3E3),
    whitePiece: Color(0xFFFFFAEF),
    blackPiece: Color(0xFF26324C),
    selected: Color(0x668DC8FF),
    selectedBorder: Color(0xFFFFD47A),
    lastMove: Color(0xD0FFE28A),
    target: Color(0x662C405D),
    captureRing: Color(0x992C405D),
    textureAlpha: 0.05,
    backdropTop: Color(0xFF2E5171),
    backdropBottom: Color(0xFF0F1C2D),
    backdropAccent: Color(0xFFFFD47A),
    backdropShadow: Color(0xFF122038),
    panelTint: Color(0xFF1D2C3E),
    backdropAsset: 'assets/chess/themes/sky-citadel.png',
  ),
};

BoardThemeStyle boardThemeStyle(BoardThemeId id) {
  return boardThemeStyles[id] ?? boardThemeStyles[BoardThemeId.classicWood]!;
}
